<?php

/**
 * @file
 * Custom functions for Views Bootstrap.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views_bootstrap_multi_item\ViewsBootstrapMultiItem;

/**
 * Implements hook_help().
 */
function views_bootstrap_multi_item_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.views_bootstrap_multi_item':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <a href="https://www.drupal.org/project/views_bootstrap">Views Bootstrap module</a> adds styles to Views to output the results of a view as several common <a href="http://getbootstrap.com/components/">Twitter Bootstrap</a> components.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('<a href="/admin/structure/views/add">Create a view</a> using one of the following styles:') . '</p>';
      $output .= '<ul>';
      $output .= '<li>' . t('<a href="https://getbootstrap.com/docs/5.1/components/carousel/">Carousel</a>') . '</li>';
      $output .= '<ul>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function views_bootstrap_multi_item_theme() {
  return ViewsBootstrapMultiItem::getThemeHooks();
}
